### PR TITLE
2024-05-16 Interest Rate Update

### PR DESCRIPTION
**Pull request by hexonaut**
Lower spread to make DAI borrow APY 9%.

To the new reviewers: You may notice that the DAI Interest Rate Model (IRM) is already configured to track the DSR, however, Maker wants exact APY targets and the spread is measured in APR which is why we need to adjust the spread instead of being able to just reuse the same IRM.

### CODE REVIEW

**Review by lucas-manuel — COMMENTED** [review]
Reviewed:
- Addresses
- Spell logic
- Tests

All LGTM so far, small amount of logic. Will re-review after links are posted and any additional logic is added.

**Review by lucas-manuel — APPROVED** [review]
Alright LGTM,

Confirmed rates changes against new forum post and matches.

**Review by barrutko — APPROVED** [review]
LGTM. Good to deploy.

**Review by 0xShaito — APPROVED** [review]
Bytecode of the new DAI IRM matches old one except the target amount (79fb3e02cbe87c3747b80 vs 77c6091704a6029f39d00) ✅

The amount in the new DAI IRM matches the calculated one (79fb3e02cbe87c3747b80 == 9216655128763325601840000) ✅

Tests sufficiently cover the correct cases ✅

Tests run correctly locally ✅

**Comment by hexonaut** [comment]
Spell is deployed: 0x901E4450f01ae1A2615E384b9104888Cb9Cb02FF

Awaiting final confirmation.

**Review by lucas-manuel — APPROVED** [review]
LGTM!

**Review by barrutko — APPROVED** [review]
LGTM

**Comment by RedLikeRosesss** [comment]
Codes match each other. LGTM

**Review by 0xShaito — APPROVED** [review]
Looks good to merge to me!

**Pull request merged**
