### PR TITLE
July 25th, 2024 Spell

### PR DESCRIPTION
**Pull request by barrutko**

### CODE REVIEW

**Comment by RedLikeRosesss** [comment]
[Spell - 25 July 2024 - Before Deployment.pdf](https://github.com/user-attachments/files/16286227/Spell.-.25.July.2024.-.Before.Deployment.pdf)
LGTM

**Review by 0xShaito — COMMENTED** [review]
- address for PT Ethena sUSDE 24OCT2024 is correct
- lltv is correct at 86%
- cap is correct at 100_000_000 DAI
- tests are green and are sufficient

LGTM!

**Review by RedLikeRosesss — DISMISSED** [review]

**Comment by RedLikeRosesss** [comment]
[Spell - 25 July 2024 - After Deployment.pdf](https://github.com/user-attachments/files/16296947/Spell.-.25.July.2024.-.After.Deployment.pdf)
LGTM

**Review by RedLikeRosesss — APPROVED** [review]

**Review by 0xShaito — DISMISSED** [review]
The deployed contract matches the bytecode in the spell ✅ 

Good to merge!

**Review by RedLikeRosesss — APPROVED** [review]

**Review by 0xShaito — DISMISSED** [review]
New oracle is correct. 

1 PT_SUSDE_24OCT2024 at maturity = 1 USDe. 
The difference in value between the PT and USDe before maturity is protected by the selected lltv (86%).

LGTM

**Review by 0xShaito — APPROVED** [review]

**Review by RedLikeRosesss — APPROVED** [review]

**Pull request merged**
